Algoritmo "ContagemRegressiva2em2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/09/2020
Var
   // Seção de Declarações das variáveis
   i, n: inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para i de 50 até 0 passo -2 faça
      escreval (i)
   fimpara
Fimalgoritmo