Algoritmo "Numeros Multiplos de 3 e 5"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/10/2020
Var
   // Seção de Declarações das variáveis
   num, i: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva ("Digite um número: ")
   leia (num)
   para i de 0 ate num passo 15 faça
      se (i>0) então
         escreva (i)
      fimse
   fimpara
Fimalgoritmo