Algoritmo "TABUADA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/09/2020
Var
// Seção de Declarações das variáveis 
i, tab: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para i de 1 até 30 passo 1 faça
tab <- 7*i
escreval (" 7 x",i,"=",tab)
fimpara
Fimalgoritmo